### PR TITLE
Add Github Pages and MetaMask

### PR DESCRIPTION
**Pull request by OR13**
I still need to add a few things to the readme, and we need to decide how to talk about the demo part, or if you will host your own version, like I did.

### CODE REVIEW

**Comment by OR13** [comment]
I cleaned up some of my mess, and added back support for the network configuration the way it was before.

The only real changes are related to using callbacks instead of sync methods (MetaMask and web3 provider engine don't support the sync methods, and you should avoid them for this reason).

There is an alert in the index.html which checks for meta mask... its not strictly speaking required, it works the same way it did before.

Regarding the demo, I left my deployment in there. It should be possible for you to deploy github pages and update the demo link in the readme. I added instructions for custom domains names, like I setup.

If there are any really big features you are thinking about, I'd like to know now. I may do some restructuring and styling changes that will make PRs harder in the future.

**Comment by OR13** [comment]
Sorry these commits suck. I was not thinking about anyone else reading them... as usual.

**Comment by fabiohild** [comment]
Thanks Orientation, I'm currently out of town for an event but will.merge
your changes when I get back.

I have no further plans for this explorer. I actually made it for another
block chain, but since it wasn't ready at the time I made it using web3
just so I'd have some data to design the front end.

Thanks a lot!

Fábio

**Comment by fabiohild** [comment]
Not at all Orie, they are looking good, I'll merge them soon. Thanks!

**Pull request merged**
